# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]

target 'BigChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for BigChat
  pod 'GoogleSignIn'
 pod 'FBSDKLoginKit'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
  target 'BigChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  end

  target 'BigChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BigChat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BigChat-tvOS

  target 'BigChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
